---
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  definition-is-used:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install -e .
      - name: assert-python-definition-is-used
        run: >-
          assert-python-definition-is-used
          src
          --consumer src
          --consumer test
          --verbose
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install pytest -e .
      - name: E2E tests
        run: python3 -m pytest test/e2e/ --verbose --pythonwarnings=error
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install pytest pytest-cov -e .
      - name: Integration tests
        run: |
          python3 -m pytest test/integration/ \
            --verbose --pythonwarnings=error \
            --cov=assert_python_definition_is_used \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  jscpd-src:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install -g jscpd
      - name: jscpd (src)
        run: jscpd --pattern "**/*.py" --threshold 0 --reporters console src/
  jscpd-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install -g jscpd
      - name: jscpd (test)
        run: jscpd --pattern "**/*.py" --threshold 0 --reporters console test/
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install -g markdownlint-cli
      - name: markdownlint
        run: markdownlint '*.md'
  mypy-src:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install mypy -e .
      - name: mypy (src)
        run: python3 -m mypy --strict src/
  mypy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install mypy pytest -e .
      - name: mypy (test)
        run: python3 -m mypy test/
  no-inline-directives:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install assert-no-inline-directives
      - name: assert-no-inline-directives
        run: >-
          assert-no-inline-directives
          --tools pylint,mypy,yamllint
          --verbose
          ${{ github.workspace }}/**/*
  no-linter-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install assert-no-linter-config-files
      - name: assert-no-linter-config-files
        run: >-
          assert-no-linter-config-files
          --linters pylint,mypy,yamllint
          --verbose
          ${{ github.workspace }}
  one-assert-per-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install assert-one-assert-per-pytest
      - name: assert-one-assert-per-pytest
        run: >-
          assert-one-assert-per-pytest
          --verbose
          ${{ github.workspace }}/test
  pylint-src:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install pylint -e .
      - name: pylint (src)
        run: python3 -m pylint src/ --fail-on=C,R,W --fail-under=10.0
  pylint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install pylint pytest -e .
      - name: pylint (test)
        run: python3 -m pylint test/ --fail-on=C,R,W --fail-under=10.0
  release:
    if: github.event_name == 'push'
    needs:
      - definition-is-used
      - e2e-tests
      - integration-tests
      - jscpd-src
      - jscpd-test
      - markdownlint
      - mypy-src
      - mypy-test
      - no-inline-directives
      - no-linter-configs
      - one-assert-per-pytest
      - pylint-src
      - pylint-test
      - unit-tests
      - yamllint
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - id: version
        name: Generate version from UTC time
        run: echo "version=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      - name: Create tag
        run: git tag "v${{ steps.version.outputs.version }}"
      - name: Install build tools
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Push tag
        run: git push origin "v${{ steps.version.outputs.version }}"
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Create GitHub Release
        run: |
          gh release create "v${{ steps.version.outputs.version }}" \
            --generate-notes
      - name: Update latest tag
        run: |
          git tag -f latest
          git push origin latest --force
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install pytest pytest-cov -e .
      - name: Unit tests
        run: |
          python3 -m pytest test/unit/ \
            --verbose --pythonwarnings=error \
            --cov=assert_python_definition_is_used \
            --cov-branch \
            --cov-report=term-missing \
            --cov-fail-under=100
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install yamllint
      - name: yamllint
        run: |
          EMPTY_LINES='empty-lines: {max: 0, max-start: 0, max-end: 1}'
          KEY_ORDERING='key-ordering: enable'
          TRUTHY='truthy: {allowed-values: ["true", "false", "on"]}'
          RULES="$EMPTY_LINES, $KEY_ORDERING, $TRUTHY"
          shopt -s globstar
          yamllint --strict --format github \
            --config-data "{extends: default, rules: {$RULES}}" \
            *.yml **/*.yml
name: release
on:
  pull_request:
    branches:
      - main
    paths:
      - "*.md"
      - ".github/workflows/release.yml"
      - "action.yml"
      - "pyproject.toml"
      - "src/**"
      - "test/**"
  push:
    branches:
      - main
    paths:
      - "*.md"
      - ".github/workflows/release.yml"
      - "action.yml"
      - "pyproject.toml"
      - "src/**"
      - "test/**"
